br/com/mentoria/java/Entrega.java
> Este PR cria a classe entrega com seus atributos, métodos getters e setters e o construtor de inicialização dos atributos.
---
Adicione o link do card relacionado a esta tarefa.
> [Criar classe Entrega](https://github.com/users/GustavodeJesus/projects/1/views/3?pane=issue&itemId=99009962&issue=GustavodeJesus%7Cmentoria-java%7C5)
---
=> feat: Criar classe Entrega

br/com/mentoria/java/Pessoa.java
> _Correção da atribuição do atributo endereço.
---
> _Exemplo:_
> - Atualizada atribuição de endereço
=> Fix: correção de atribuição this.endereco

br/com/mentoria/java/Entrega.java
> Este PR corrige a classe Entrega
---
=> fix: Correção classe Entrega

br/com/mentoria/java/Vendedor.java
> _ Este PR corrige o método construtor da classe vendedor.
---
> _Exemplo:_
> - foi corrigido declaração no método construtor
=> Fix: foi corrigido declaração no método construtor

src/main/java/br/com/mentoriajava/produtos/Produto.java
>  Este PR adiciona a classe Produto.java, classe essa que será necessária para utilizarmos na futura classe Pedido.
Atributos:
codigoProduto;
nomeProduto;
categoriaProduto;
precoProduto;
estoqueProduto;
Métodos:
getters e setters.
---
> https://github.com/users/GustavodeJesus/projects/1/views/3?pane=issue&itemId=109216289&issue=GustavodeJesus%7Cmentoria-java%7C50
---
- Nova classe adicionada
=> feature: produto - task: criação da classe Produto

src/main/java/br/com/mentoriajava/database/ProdutoDataSource.java, src/main/java/br/com/mentoriajava/produtos/Produto.java
> Criado a classe ProdutoDataSource, com uma instancia única (Singleton) para impedir ter mais de uma lista de produtos no sistema. Foi implementado 10 exemplos de produtos na lista.
---
> https://github.com/users/GustavodeJesus/projects/1/views/3?pane=issue&itemId=109216648&issue=GustavodeJesus%7Cmentoria-java%7C51
=> feat(produto): criação do ProdutoDataSource

src/main/java/br/com/mentoriajava/database/ClienteDataSource.java
Este PR cria a classe ClienteDataSource.
---
Adicione o link do card relacionado a esta tarefa.
> _Exemplo:_ [Card da atividade](https://github.com/GustavodeJesus/mentoria-java/issues/46)
---
=> task: criado classe ClienteDataSource

src/main/java/br/com/mentoriajava/database/VendedorDataSource.java
> _ Este PR implementa a classe VendedoresDataSource.
---
> _ [Card no GitHub](https://github.com/GustavodeJesus/mentoria-java/issues/41)
---
=> task: Criar VendedoresDataSource

src/main/java/br/com/mentoriajava/produtos/ProdutosScreen.java
> Este PR implementa as configurações iniciais da tela de cadastro de produto, estilo, espaçamento e VBox iniciando o formulário de cadastro.
---
> https://github.com/GustavodeJesus/mentoria-java/issues/52
---
=> task: Atualização Produto Screen

src/main/java/br/com/mentoriajava/clientes/ClientesScreen.java
> Este PR realiza algumas alterações no layout da tela de cadastro do cliente.
---
> _Exemplo:_ [Card no Projeto](https://github.com/GustavodeJesus/mentoria-java/issues/47)
---
=> task: configurado layout da tela de cadastro de cliente (ClientesScreen)

src/main/java/br/com/mentoriajava/vendedores/VendedoresScreen.java
Mudanças realizadas.
> _ Este PR atualiza a tela de cadastro de vendedores agregando um corpo pronto para receber um formulário e lista de vendedores.
---
> _ [Card no GitHub](https://github.com/GustavodeJesus/mentoria-java/issues/64)
---
> - Atualizado código da tela
> - Implementado funcionalidades de organização
=> Task: #64 Atualizado a tela cadastro de vendedor 

src/main/java/br/com/mentoriajava/database/VendedorDataSource.java, src/main/java/br/com/mentoriajava/vendedores/StatusVendedorEnum.java, src/main/java/br/com/mentoriajava/vendedores/VendedoresScreen.java
>_ Este PR adiciona formulário a tela de cadastro de vendedor.
---
Adicione o link do card relacionado a esta tarefa.
> _ [Card do GitHub](https://github.com/GustavodeJesus/mentoria-java/issues/35)
---
> - Criação de formulário
=> criado formulario cadastrar vendedor

src/main/java/br/com/mentoriajava/clientes/ClientesScreen.java
> Este PR configura o formulário de cadastro de novos clientes.
---
> [Card no Projeto](https://github.com/GustavodeJesus/mentoria-java/issues/40)
---
=> task: configurado formulario para cadastro de clientes.

src/main/java/br/com/mentoriajava/produtos/ProdutosScreen.java
> Este PR adiciona um pop-up confirmando que o produto foi cadastrado.
---
> https://github.com/users/GustavodeJesus/projects/1/views/1?pane=issue&itemId=109217332&issue=GustavodeJesus%7Cmentoria-java%7C56
---
> - Pop-up visual informando que o produto foi cadastrado
=> task: Pop-up confirmando cadastro de produto

src/main/java/br/com/mentoriajava/database/VendedorDataSource.java, src/main/java/br/com/mentoriajava/home/HomeApp.java, src/main/java/br/com/mentoriajava/vendedores/ListagemVendedoresScreen.java, src/main/java/br/com/mentoriajava/vendedores/VendedoresScreen.java
> _ Este PR adiciona a funcionalidade de listagem de vendedores e valida todas as funcionalidades criadas.
---
> _ [#37 ](https://github.com/GustavodeJesus/mentoria-java/issues/37)
---
> - Adicionado listagem dos vendedores
> - Criado botões de ações (vendedores cadastrados e retornar a tela cadastrar)
> - Correção de erros de código
> - Validação das funcionalidades criadas
=> Task: Criado listagem de vendedores

src/main/java/br/com/mentoriajava/cupons/Cupom.java, src/main/java/br/com/mentoriajava/cupons/CuponsEnum.java, src/main/java/br/com/mentoriajava/database/CupomDataSource.java
> _ Neste PR foi implementado o cupomDataSource.
---
Adicione o link do card relacionado a esta tarefa.
> _[Card no github](https://github.com/GustavodeJesus/mentoria-java/issues/59)
---
=> task: criado cupomDataSource

src/main/java/br/com/mentoriajava/database/VendedorDataSource.java, src/main/java/br/com/mentoriajava/home/HomeApp.java, src/main/java/br/com/mentoriajava/vendedores/ListagemVendedoresScreen.java, src/main/java/br/com/mentoriajava/vendedores/StatusVendedorEnum.java, src/main/java/br/com/mentoriajava/vendedores/Vendedor.java, src/main/java/br/com/mentoriajava/vendedores/VendedoresScreen.java
> _Este PR adiciona a tela de cadastro de Vendedores, integrando com a classe VendedoresDataSource que atua como uma simulação de Banco de Dados. Cadastrar e remover funcionando corretamente, validação dos campos obrigatórios quando não preenchidos.
---
> _ [Card no GitHub](https://github.com/GustavodeJesus/mentoria-java/issues/33)
---
> - Tela de cadastro
> - Tela de listagem
> - Criado DataSource
> - Funcionalidades de navegação
=> feature: criar tela cadastro vendedores

br/com/mentoria/java/Main.java, src/main/java/br/com/mentoriajava/PedidoApp.java
> Este PR cria uma tabela de listagem dos clientes cadastrados.
---
> [Card no Projeto](https://github.com/GustavodeJesus/mentoria-java/issues/48)
---
=> task: criar tabela listagem cliente

br/com/mentoria/java/Main.java, src/main/java/br/com/mentoriajava/clientes/ClientesScreen.java
> Este PR adiciona o PopUp de confirmação de cadastro de novos clientes.
---
> [Link do Card] (https://github.com/GustavodeJesus/mentoria-java/issues/43)
---
=> task: criar popup confirmacao cadastro

src/main/java/br/com/mentoriajava/produtos/ProdutosScreen.java
> Alteração do titulo da tela de cadastro de produtos.
---
=> chore: alteração do titulo da tela de produtos
